// <auto-generated />
using System;
using AltaVisual.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AltaVisual.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260408233417_AddMetrosUsadosAdesivo")]
    partial class AddMetrosUsadosAdesivo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AltaVisual.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("AltaVisual.Models.ProdutoGrafico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<int?>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorFinal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("Produtos");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ProdutoGrafico");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AltaVisual.Models.Adesivo", b =>
                {
                    b.HasBaseType("AltaVisual.Models.ProdutoGrafico");

                    b.Property<double>("AlturaCm")
                        .HasColumnType("float");

                    b.Property<double>("LarguraCm")
                        .HasColumnType("float");

                    b.Property<decimal>("MetrosQuadradosUsados")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.ToTable("Produtos", t =>
                        {
                            t.Property("Quantidade")
                                .HasColumnName("Adesivo_Quantidade");
                        });

                    b.HasDiscriminator().HasValue("Adesivo");
                });

            modelBuilder.Entity("AltaVisual.Models.Banner", b =>
                {
                    b.HasBaseType("AltaVisual.Models.ProdutoGrafico");

                    b.Property<double>("Altura")
                        .HasColumnType("float");

                    b.Property<double>("Largura")
                        .HasColumnType("float");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Banner");
                });

            modelBuilder.Entity("AltaVisual.Models.ProdutoGrafico", b =>
                {
                    b.HasOne("AltaVisual.Models.Pedido", null)
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId");
                });

            modelBuilder.Entity("AltaVisual.Models.Pedido", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
